name: periodic health check

on:
  schedule:
    - cron: "0 0 */31 * *"

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: "https://pokedex322.herokuapp.com/health"
